### ISSUE TITLE
[Deepfake Detection] KaggleのDiscussionからの情報収集

### ISSUE THREAD

**Issue by akitenkrad** [akitenkrad/arise_kaggle#3]
Task
---
- [ ] Kaggleのコンペのページでやり取りされている情報からめぼしいものを見つけて共有

Output
---
- 見つけたものから，このIssueに張り付ける
- MTGのときにコンペ参加者に共有

**Comment by yamasaki-yu** [comment]
test
testtt
testttt

**Comment by yamasaki-yu** [comment]
役に立ちそうな論文集について

【元記事タイトル】
　Useful Papers

【元記事リンク】
https://www.kaggle.com/c/deepfake-detection-challenge/discussion/121183

【概要】
　以下の論文集へのリンク
　
・Unmasking DeepFakes with simple Features
　単純な方法でのDeepfakeのマスク除去について

・Deep Learning for Deepfakes Creation and Detection
　Deepfakeの作成と検出のための深層学習

・Exposing DeepFake Videos By Detecting Face Warping Artifacts
　顔のゆがみを検出してDeepFakeビデオを暴く

・awesome-deepfakes
　すごいディープフェイク

・MesoNet: a Compact Facial Video Forgery Detection Network
　MesoNet:コンパクトな顔ビデオ偽造検出ネットワーク

・USE OF A CAPSULE NETWORK TO DETECT FAKE IMAGES AND VIDEOS
　Fake画像・動画の検出のためのカプセルネットワーク利用

・Protecting World Leaders Against Deep Fakes
　ディープフェイクから世界の指導者を守る

・FaceForensics++: Learning to Detect Manipulated Facial Images
　顔の法医学：加工された顔画像検出の学習

・Towards deepfake detection that actually works
　実動作するディープフェイクに向けて

・DeepFake Audio Detection
　ディープフェイク音声の検出


【コメント】
ディープフェイクに関する基礎的な技術の紹介です

**Comment by yamasaki-yu** [comment]
最新論文集

【元記事タイトル】
State of the Art. Deepfake Detection references.

【元記事リンク】
https://www.kaggle.com/c/deepfake-detection-challenge/discussion/121223

【概要】
　最新の深層学習手法の紹介
　
【コメント】
　高度な最新手法の紹介が主です。
　自分たちのソースに盛り込むのは難しい内容が多い気がします。
　あくまで参考という感じです。

**Comment by yamasaki-yu** [comment]
環境整備からデータ解凍までの手順

【元記事タイトル】
First steps to get started.

【元記事リンク】
https://www.kaggle.com/c/deepfake-detection-challenge/discussion/121695

【概要】
DeepFake問題のとっかかりとして、
環境整備～データセット解凍までの手筈をかんたんに解説

①開発環境の用意
　AWSにVM環境を用意。
　ストレージの容量が少ないと全データセットをDLできない点に注意。

②データセットの保存
　wgetコマンドを使用してDL。
　資格情報の取得等、一工夫いるらしい。

③データの回答
　49ファイルあるデータの解凍は、スクリプトを使用して実行。
　unzipでの解凍は成功/失敗がわからず、プロセスバーも出ないので
　筆者としては非推奨とのこと。

その他エラー対応については、ディスカッションの中で情報でてます
　
【コメント】
　②,③あたりは我々のタスクとしても参考になると思います。
　以下、②に関して福嶋さんからの追加情報↓


②に関しては、gcp上で一回試したことがあります。
cookieの情報がないと、wgetではkaggle上にログインができないため、ローカルで一度kaggleにログインしてからcookieファイルを取得して、分析環境上にアップロードする必要があります。
↓以下のChromeのAddOnを使用してcookieファイルをインストールしました。
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=ja

**Comment by yamasaki-yu** [comment]
動画読み込みの高速化

【元記事タイトル】
Video loading optimization tips

【元記事リンク】
https://www.kaggle.com/c/deepfake-detection-challenge/discussion/122328

【概要】
・opencvで動画処理する際、フレームを間引きして処理するのであれば、
.read()でなく、grab()とretrieve()を利用したほうが高速とのこと
・ディスカッションを流し見した限り、大体30％くらいの高速化になりそう。
・ストレージの容量が少ないと全データセットをDLできない点に注意。
　
【コメント】
動画像処理の実装の基礎的な内容として参考になると思います。
ただし、フレームを間引く処理は「特定のフレームにピンポイントで出るノイズをとらえたい」みたいなニーズには答えられないと思うので、
自分たちがやりたいことに対して本ディスカッションの手法が妥当かは検討の余地ありかと思います。

**Comment by yamasaki-yu** [comment]
GANとDeepFakeの参考ソースコード

【元記事タイトル】
GAN and DeepFake resources

【元記事リンク】
https://www.kaggle.com/c/deepfake-detection-challenge/discussion/121313

【概要】
GANとDeepFakeを実装する際に参考になりそうなソースコードへのリンク
　
【コメント】
GANは今回のタスクに直接役立たないとは思いますが、
我々としては「Kaggleカーネル」の項目で共有されている以下2点のソースが
参考になりそうだったのでこの記事をピックアップした次第です。
・顔検出
・動画像処理

**Comment by yamasaki-yu** [comment]
Fake音声の検出

【元記事タイトル】
Finding the fake audio

【元記事リンク】
https://www.kaggle.com/c/deepfake-detection-challenge/discussion/122785

【概要】
音声のFake検出について、オーディオのFakeラベルを用意する。

・学習セットのFake動画のうち、音声がFakeのものを探し出して、
「音声がFake」のメタデータを新たに追加した。

・動画の加工前後で、オーディオに変化があるものを「音声がFake」
と判断してラベル付与した。

・サンプルレートに変化があるFakeは実際に聞いても差が分かりやすい。
一方、サンプルレートに変化ないものは聞いてもわかりにくいとのこと。後者はノイズ除去等の処理に起因するものではないかとのこと。

・オーディオデータを見る限り、Fakeデータはデータセット中に不均一に存在するので、学習時には注意したほうが良い。
　
【コメント】
Fakeであることの定義に音声がオリジナルから異なっていることは含まないとの情報があります。
ソースは、以下のディスカッションでコンペのホスト(?)から「音声のダウンサンプリングはFakeとみなさない」というコメントですhttps://www.kaggle.com/c/deepfake-detection-challenge/discussion/121694

音声の差分がFake判別の手がかりになることはありそうですが、
福嶋さんが試しに実装して音声データ抜きでもそこそこの精度が出たという実績もあるので、音声処理は優先順位低くていいかもしれません。
